Section "ServerFlags"
    Option "DontVTSwitch" "true"
    Option "AllowMouseOpenFail" "true"
    Option "PciForceNone" "true"
    Option "AutoEnableDevices" "false"
    Option "AutoAddDevices" "false"
EndSection

Section "Module"
    Load "xorgxrdp"
EndSection

Section "InputDevice"
    Identifier "xrdp Keyboard"
    Driver "xrdpkeyb"
EndSection

Section "InputDevice"
    Identifier "xrdp Mouse"
    Driver "xrdpmouse"
EndSection

Section "Device"
    Identifier "xrdp Video Device"
    Driver "xrdpdev"
    Option "DRMDevice" ""
    Option "AllowEmptyInitialConfiguration" "true"
EndSection

Section "Screen"
    Identifier "Default Screen"
    Device "xrdp Video Device"
    DefaultDepth 24
EndSection
